packages:
  - "apps/*"
  - "packages/*"

catalog:
  tailwindcss: ^3.4.13
  typescript: ^5.6.3
  tsup: ^8.3.5
  postcss: ^8
  autoprefixer: ^10
  zod: ^3.23.8
  "@types/node": ^20

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
